(function(){
'use strict';
const el=id=>document.getElementById(id);
let aiGeneration=0;
let pendingTimer=null;
function aiOpen(){return !!el('aiChatScreen')?.classList.contains('active')}
function setRobot(state){const r=el('robotAvatar');if(!r)return;r.classList.remove('listening','thinking','speaking');if(state)r.classList.add(state)}
function setStatus(text){const b=el('aiSpeechBubble');if(b)b.textContent=String(text||'')}
function stopPending(){aiGeneration++;if(pendingTimer){clearTimeout(pendingTimer);pendingTimer=null}setRobot('');try{speechSynthesis?.cancel()}catch(e){}}
function add(role,text){if(!aiOpen())return;const box=el('chatBox');if(!box)return;const d=document.createElement('div');d.className='chat-bubble '+role;d.textContent=String(text||'');box.appendChild(d);box.scrollTop=box.scrollHeight}
function baseLang(){return String(window.currentLang||el('globalLang')?.value||'en-US').split('-')[0].toLowerCase()}
function reply(text){const raw=String(text||'').trim(),t=raw.toLowerCase(),b=baseLang();if(!raw)return'Diga ou escreva uma frase para continuar.';if(/\b(ola|oi|hello|hi|hola|bonjour|hallo|ciao)\b/i.test(t)){if(b==='es')return'Hola! Como estas? Podemos practicar juntos.';if(b==='fr')return'Bonjour ! Comment ca va ? Nous pouvons pratiquer ensemble.';if(b==='de')return'Hallo! Wie geht es dir? Wir koennen zusammen ueben.';if(b==='it')return'Ciao! Come stai? Possiamo esercitarci insieme.';if(b==='ja')return'こんにちは！一緒に練習しましょう。';if(b==='pt')return'Ola! Como voce esta? Podemos praticar juntos.';return'Hello! How are you? We can practice together.'}if(t.includes('trad'))return'Posso ajudar com traducao. Escreva a frase e diga o idioma de destino.';if(t.includes('pronun'))return'Posso ajudar com pronuncia. Fale devagar e tente novamente pelo microfone.';if(t.includes('restaurant'))return'Try: Could I see the menu, please?';if(t.includes('viagem')||t.includes('travel')||t.includes('airport'))return'Try: Where is the check-in counter?';if(b==='es')return'Entendido: '+raw+'. Continua con otra frase.';if(b==='fr')return'Compris : '+raw+'. Continuez avec une autre phrase.';if(b==='de')return'Verstanden: '+raw+'. Mach mit einem weiteren Satz weiter.';if(b==='it')return'Capito: '+raw+'. Continua con un altra frase.';if(b==='ja')return'わかりました。「'+raw+'」もう一文続けてみましょう。';return'Entendi: '+raw+'. Continue com mais uma frase e eu acompanho sua pratica.'}
window.speakAIWithMotion=function(text){const my=++aiGeneration;setStatus(text);if(!('speechSynthesis'in window)){setRobot('');return}try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text||''));u.lang=window.currentLang||el('globalLang')?.value||'en-US';const voices=speechSynthesis.getVoices?.()||[],base=u.lang.split('-')[0].toLowerCase();u.voice=voices.find(v=>v.lang===u.lang)||voices.find(v=>String(v.lang||'').toLowerCase().startsWith(base))||null;u.onstart=()=>{if(my===aiGeneration&&aiOpen())setRobot('speaking')};const done=()=>{if(my===aiGeneration)setRobot('')};u.onend=done;u.onerror=done;speechSynthesis.speak(u)}catch(e){setRobot('')}};
window.askAI=function(message){const text=String(message||'').trim();if(!text)return;const my=++aiGeneration;add('user',text);setRobot('thinking');setStatus('Pensando...');pendingTimer=setTimeout(()=>{pendingTimer=null;if(my!==aiGeneration||!aiOpen())return;const r=reply(text);add('ai',r);window.speakAIWithMotion(r)},180)};
window.sendTypedMessage=function(){const i=el('chatInput');if(!i)return;const t=i.value.trim();if(!t)return;i.value='';window.askAI(t)};
const oldStart=window.startAIChat;window.startAIChat=function(){stopPending();try{oldStart?.()}catch(e){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id==='aiChatScreen'))}setStatus('Pronto para conversar por voz ou texto.')};
const oldHome=window.goToHome;window.goToHome=function(){stopPending();try{return oldHome?.()}catch(e){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id==='homeScreen'))}};
const input=el('chatInput');if(input&&!input.dataset.aiFixed){input.dataset.aiFixed='1';input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();window.sendTypedMessage()}})}
window.addEventListener('error',()=>setRobot(''));window.addEventListener('unhandledrejection',()=>{setRobot('');setStatus('O assistente se recuperou de uma falha. Tente novamente.')});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopPending()});
})();